import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../repositories/purchase_repository.dart';

class PurchaseLine { String productId=''; String productName=''; int quantity=1; double purchaseCost=0, tradeOffer=0, purchaseDiscount=0, salePrice=0; double get gross=>quantity*purchaseCost; double get discountAmount=>gross*purchaseDiscount/100; double get net=>gross-discountAmount; }

class PurchasesScreen extends StatefulWidget { const PurchasesScreen({super.key}); @override State<PurchasesScreen> createState()=>_PurchasesScreenState(); }
class _PurchasesScreenState extends State<PurchasesScreen> {
  final repo=PurchaseRepository(); final vendor=TextEditingController(); final bill=TextEditingController(); final paid=TextEditingController(text:'0'); final bd=TextEditingController(text:'0'); final exp=TextEditingController(text:'0');
  DateTime date=DateTime.now(); String? accountId; List<Map<String,dynamic>> products=[], accounts=[]; final lines=<PurchaseLine>[PurchaseLine()]; bool loading=true,saving=false;
  @override void initState(){super.initState();_load();}
  @override void dispose(){for(final c in [vendor,bill,paid,bd,exp])c.dispose();super.dispose();}
  Future<void> _load() async { try { products=await repo.products(); accounts=await repo.accounts(); if(accounts.isNotEmpty)accountId=accounts.first['id'].toString(); } catch(e){_snack('Database: $e');} setState(()=>loading=false); }
  double n(TextEditingController c)=>double.tryParse(c.text.replaceAll(',','').trim())??0;
  double get subtotal=>lines.fold(0,(a,x)=>a+x.gross); double get pdisc=>lines.fold(0,(a,x)=>a+x.discountAmount); double get after=>subtotal-pdisc; double get bda=>after*n(bd)/100; double get ea=>(after-bda)*n(exp)/100; double get total=>after-bda+ea; double get bal=>total-n(paid);
  InputDecoration d(String x)=>InputDecoration(labelText:x,isDense:true,border:const OutlineInputBorder());
  void _snack(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
  Future<void> _save() async { if(accountId==null){_snack('Payment Account منتخب کریں۔');return;} if(lines.any((x)=>x.productId.isEmpty||x.quantity<=0)){_snack('ہر لائن میں Product اور Quantity درج کریں۔');return;} setState(()=>saving=true); try { await repo.save(vendorName:vendor.text,billNumber:bill.text,accountId:accountId!,date:date,billDiscountPercent:n(bd),expensesPercent:n(exp),paidAmount:n(paid),lines:lines.map((x)=>PurchaseLineInput(productId:x.productId,quantity:x.quantity,purchaseCost:x.purchaseCost,tradeOfferPercent:x.tradeOffer,purchaseDiscountPercent:x.purchaseDiscount,salePrice:x.salePrice)).toList()); _snack('Purchase saved successfully. Stock, vendor ledger, account and batch updated.'); _clear(); } catch(e){_snack(e.toString().replaceFirst('Exception: ',''));} setState(()=>saving=false); }
  void _clear(){vendor.clear();bill.clear();paid.text='0';bd.text='0';exp.text='0';date=DateTime.now();lines..clear()..add(PurchaseLine());setState((){});}
  @override Widget build(BuildContext c){ if(loading)return const Center(child:CircularProgressIndicator()); return SingleChildScrollView(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Row(children:[const Expanded(child:Text('Purchase / Vendor Bill',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold))),OutlinedButton.icon(onPressed:()=>_previousBills(c),icon:const Icon(Icons.history),label:const Text('Previous Bills')),const SizedBox(width:8),OutlinedButton.icon(onPressed:()=>_vendorHistory(c),icon:const Icon(Icons.person_search),label:const Text('Vendor History'))]),const SizedBox(height:16),
    Card(child:Padding(padding:const EdgeInsets.all(16),child:Wrap(spacing:12,runSpacing:12,children:[SizedBox(width:250,child:TextField(controller:vendor,decoration:d('Vendor *'))),SizedBox(width:180,child:TextField(controller:bill,decoration:d('Bill Number *'))),SizedBox(width:170,child:InputDecorator(decoration:d('Date'),child:InkWell(onTap:_pickDate,child:Text(DateFormat('dd-MM-yyyy').format(date))))),SizedBox(width:230,child:DropdownButtonFormField<String>(value:accountId,decoration:d('Payment Account *'),items:accounts.map((a)=>DropdownMenuItem(value:a['id'].toString(),child:Text(a['name'].toString()))).toList(),onChanged:(v)=>setState(()=>accountId=v)))]))),const SizedBox(height:16),
    Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Product Details',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:12),SingleChildScrollView(scrollDirection:Axis.horizontal,child:DataTable(columns:const[DataColumn(label:Text('Product')),DataColumn(label:Text('Qty')),DataColumn(label:Text('Purchase Cost')),DataColumn(label:Text('Trade Offer %')),DataColumn(label:Text('Purchase Discount %')),DataColumn(label:Text('Sale Cost')),DataColumn(label:Text('Net')),DataColumn(label:Text(''))],rows:List.generate(lines.length,_row))),const SizedBox(height:10),FilledButton.icon(onPressed:()=>setState(()=>lines.add(PurchaseLine())),icon:const Icon(Icons.add),label:const Text('Add Product'))]))),const SizedBox(height:16),
    Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('Invoice Details',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold))),const SizedBox(height:12),Wrap(spacing:12,runSpacing:12,children:[SizedBox(width:210,child:TextField(controller:bd,keyboardType:TextInputType.number,onChanged:(_)=>setState((){}),decoration:d('Bill Discount %'))),SizedBox(width:210,child:TextField(controller:exp,keyboardType:TextInputType.number,onChanged:(_)=>setState((){}),decoration:d('Expenses %'))),SizedBox(width:210,child:TextField(controller:paid,keyboardType:TextInputType.number,onChanged:(_)=>setState((){}),decoration:d('Paid Amount')))]),const SizedBox(height:14),Align(alignment:Alignment.centerRight,child:SizedBox(width:380,child:Column(children:[_sum('Subtotal',subtotal),_sum('Product Discount',pdisc),_sum('Bill Discount',bda),_sum('Expenses',ea),const Divider(),_sum('Total Amount',total,true),_sum('Paid Amount',n(paid)),_sum('Balance',bal,true)])))]))),const SizedBox(height:16),Row(mainAxisAlignment:MainAxisAlignment.end,children:[OutlinedButton(onPressed:saving?null:_clear,child:const Text('Cancel')),const SizedBox(width:10),FilledButton.icon(onPressed:saving?null:_save,icon:saving?const SizedBox(width:16,height:16,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save),label:Text(saving?'Saving...':'Save Purchase'))]) ])); }
  DataRow _row(int i){final x=lines[i];return DataRow(cells:[DataCell(SizedBox(width:250,child:DropdownButton<String>(isExpanded:true,value:x.productId.isEmpty?null:x.productId,hint:const Text('Select product'),items:products.map((p)=>DropdownMenuItem(value:p['id'].toString(),child:Text('${p['name']}${p['brand']==null?'':' — ${p['brand']}'}'))).toList(),onChanged:(v){setState(()=>x.productId=v!);final p=products.firstWhere((z)=>z['id'].toString()==v);x.productName=p['name'].toString();x.purchaseCost=(p['purchase_price'] as num?)?.toDouble()??0;x.salePrice=(p['retail_price'] as num?)?.toDouble()??0;});})),DataCell(_numField(x.quantity.toString(),(v)=>setState(()=>x.quantity=int.tryParse(v)??0))),DataCell(_numField(x.purchaseCost.toStringAsFixed(2),(v)=>setState(()=>x.purchaseCost=double.tryParse(v)??0))),DataCell(_numField(x.tradeOffer.toStringAsFixed(2),(v)=>setState(()=>x.tradeOffer=double.tryParse(v)??0))),DataCell(_numField(x.purchaseDiscount.toStringAsFixed(2),(v)=>setState(()=>x.purchaseDiscount=double.tryParse(v)??0))),DataCell(_numField(x.salePrice.toStringAsFixed(2),(v)=>setState(()=>x.salePrice=double.tryParse(v)??0))),DataCell(Text('Rs. ${x.net.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.bold))),DataCell(IconButton(onPressed:lines.length==1?null:()=>setState(()=>lines.removeAt(i)),icon:const Icon(Icons.delete_outline))) ]);}
  Widget _numField(String initial,void Function(String) cb)=>SizedBox(width:125,child:TextFormField(initialValue:initial,onChanged:cb,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(isDense:true,border:OutlineInputBorder())));
  Widget _sum(String l,double v,[bool strong=false])=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(children:[Expanded(child:Text(l,style:TextStyle(fontWeight:strong?FontWeight.bold:FontWeight.normal))),Text('Rs. ${v.toStringAsFixed(2)}',style:TextStyle(fontWeight:strong?FontWeight.bold:FontWeight.w600))]));
  Future<void> _pickDate() async{final x=await showDatePicker(context:context,initialDate:date,firstDate:DateTime(2020),lastDate:DateTime(2100));if(x!=null)setState(()=>date=x);}
  Future<void> _previousBills(BuildContext c)async{final rows=await repo.previousBills(vendor.text);if(!mounted)return;showDialog(context:c,builder:(_)=>AlertDialog(title:Text(vendor.text.isEmpty?'Previous Bills':'Previous Bills — ${vendor.text}'),content:SizedBox(width:780,height:430,child:rows.isEmpty?const Center(child:Text('No previous bills found.')):ListView.builder(itemCount:rows.length,itemBuilder:(_,i){final r=rows[i];return ListTile(title:Text('${r['bill_number']??'—'}  •  ${r['vendor']??''}'),subtitle:Text('${DateFormat('dd-MM-yyyy').format(DateTime.parse(r['date'].toString()))}  |  Total Rs. ${r['total_amount']}  |  Paid Rs. ${r['paid_amount']}  |  Balance Rs. ${r['balance_amount']}'));})),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]));}
  Future<void> _vendorHistory(BuildContext c)async{final s=await repo.vendorSummary(vendor.text);if(!mounted)return;showDialog(context:c,builder:(_)=>AlertDialog(title:Text('Vendor History — ${s['name']}'),content:SizedBox(width:700,height:250,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Opening Balance: Rs. ${s['opening_balance']}'),Text('Total Purchases: Rs. ${s['purchases']}'),Text('Total Paid: Rs. ${s['paid']}'),Text('Current Balance: Rs. ${s['balance']}'),const SizedBox(height:18),const Text('Previous Bills can be opened from “Previous Bills”.',style:TextStyle(color:Colors.grey))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]));}
}
